apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-headless-service-k8s-client
  labels:
    app: hello-headless-service-k8s-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-headless-service-k8s-client
  template:
    metadata:
      labels:
        app: hello-headless-service-k8s-client
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: server-user
      containers:
      - name: hello-headless-service-k8s-client
        image: kaixin-registry:5001/hello-headless-service-k8s-client:v1.0
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            value: "default"
          - name: GRPC_SERVER_ADDR
            value: "dns:///hello-headless-service-k8s-server.default.svc.cluster.local"
          - name: GRPC_SERVER_PORT
            value: "50051"
          - name: CLIENT_CONNECTION
            value: "3"
          - name: STREAMER_PER_CONNECTION
            value: "10"
          - name: REQUEST_PER_CLIENT
            value: "500"
        resources:
          limits:
            cpu: "200m"
            memory: "250Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"